---
name: Color RectalCancer
author: xiaochen
description: Color RectalCancer
topic: Color RectalCancer
algorithm: SENet
language: python3
virtualenv: flyai_env/bin/

framework: PyTorch

data:
  id: ColorRectalCancerClassification
  name: Color RectalCancer
  category: image


model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [150,150,3]
  output:
    columns:
      - name: label
        type: int
    to_type: float
    to_shape: [-1,8]


evaluate:
  score: torch_accuracy

servers:
 - id: flyai
   url: https://flyai.com
...